/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(main)': RouteRecordInfo<
      '/(main)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '/(main)/starter'
    >,
    '/(main)/starter': RouteRecordInfo<
      '/(main)/starter',
      '/starter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/authentication/auth1/forgotpwd1': RouteRecordInfo<
      '/authentication/auth1/forgotpwd1',
      '/authentication/auth1/forgotpwd1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/authentication/auth1/login1': RouteRecordInfo<
      '/authentication/auth1/login1',
      '/authentication/auth1/login1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/authentication/auth1/register1': RouteRecordInfo<
      '/authentication/auth1/register1',
      '/authentication/auth1/register1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/authentication/login': RouteRecordInfo<
      '/authentication/login',
      '/authentication/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/maintenance/error': RouteRecordInfo<
      '/maintenance/error',
      '/maintenance/error',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(main).vue': {
      routes:
        | '/(main)'
        | '/(main)/starter'
      views:
        | 'default'
    }
    'src/pages/(main)/starter.vue': {
      routes:
        | '/(main)/starter'
      views:
        | never
    }
    'src/pages/authentication/auth1/forgotpwd1.vue': {
      routes:
        | '/authentication/auth1/forgotpwd1'
      views:
        | never
    }
    'src/pages/authentication/auth1/login1.vue': {
      routes:
        | '/authentication/auth1/login1'
      views:
        | never
    }
    'src/pages/authentication/auth1/register1.vue': {
      routes:
        | '/authentication/auth1/register1'
      views:
        | never
    }
    'src/pages/authentication/login.vue': {
      routes:
        | '/authentication/login'
      views:
        | never
    }
    'src/pages/maintenance/error.vue': {
      routes:
        | '/maintenance/error'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
