/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(main)': RouteRecordInfo<
      '/(main)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '/(main)/advance/alert'
      | '/(main)/advance/basic-datatable'
      | '/(main)/advance/btn-toggle'
      | '/(main)/advance/chip-group'
      | '/(main)/advance/data-display-datatable'
      | '/(main)/advance/data-iterator'
      | '/(main)/advance/datepicker'
      | '/(main)/advance/emptystate'
      | '/(main)/advance/fileupload'
      | '/(main)/advance/floatingaction'
      | '/(main)/advance/mask-input'
      | '/(main)/advance/pagination'
      | '/(main)/advance/progress'
      | '/(main)/advance/ratings'
      | '/(main)/advance/server-side-datatable'
      | '/(main)/advance/snackbar'
      | '/(main)/advance/speeddial'
      | '/(main)/advance/steppers'
      | '/(main)/advance/timeline'
      | '/(main)/advance/timepicker'
      | '/(main)/advance/treeview'
      | '/(main)/app/calendar/'
      | '/(main)/app/chats'
      | '/(main)/app/contact/c-card'
      | '/(main)/app/contact/c-list'
      | '/(main)/app/customer/create-invoice'
      | '/(main)/app/customer/customerlist'
      | '/(main)/app/customer/order-details'
      | '/(main)/app/customer/orderlist'
      | '/(main)/app/customer/productlist'
      | '/(main)/app/customer/productreview'
      | '/(main)/app/kanban'
      | '/(main)/app/mail'
      | '/(main)/app/user/account-profile/profile1'
      | '/(main)/app/user/account-profile/profile2'
      | '/(main)/app/user/account-profile/profile3'
      | '/(main)/app/user/card/card1'
      | '/(main)/app/user/card/card2'
      | '/(main)/app/user/card/card3'
      | '/(main)/app/user/list1'
      | '/(main)/app/user/list2'
      | '/(main)/app/user/social/followers'
      | '/(main)/app/user/social/friend-requests'
      | '/(main)/app/user/social/friends'
      | '/(main)/app/user/social/gallery'
      | '/(main)/app/user/social/posts'
      | '/(main)/basic/avatar'
      | '/(main)/basic/badges'
      | '/(main)/basic/breadcrumb'
      | '/(main)/basic/cards'
      | '/(main)/basic/chip'
      | '/(main)/basic/expansion-panel'
      | '/(main)/basic/parallax'
      | '/(main)/basic/tabs'
      | '/(main)/basic/uilist'
      | '/(main)/charts/apex-chart'
      | '/(main)/charts/orgchart'
      | '/(main)/charts/pie-chart'
      | '/(main)/charts/sparklines'
      | '/(main)/dashboard/analytics'
      | '/(main)/dashboard/default'
      | '/(main)/ecommerce/checkout'
      | '/(main)/ecommerce/product/detail/[id]'
      | '/(main)/ecommerce/productlist'
      | '/(main)/ecommerce/products'
      | '/(main)/forms/FormValidation'
      | '/(main)/forms/layouts/action-bar'
      | '/(main)/forms/layouts/layouts'
      | '/(main)/forms/layouts/multi-column-forms'
      | '/(main)/forms/layouts/sticky-action-bar'
      | '/(main)/forms/plugins/clipboard'
      | '/(main)/forms/plugins/dropzone'
      | '/(main)/forms/plugins/editor'
      | '/(main)/forms/plugins/modal'
      | '/(main)/forms/plugins/tooltip'
      | '/(main)/pricing/pricing1'
      | '/(main)/pricing/pricing2'
      | '/(main)/starter'
      | '/(main)/tables/tbl-basic'
      | '/(main)/tables/tbl-dark'
      | '/(main)/tables/tbl-density'
      | '/(main)/tables/tbl-fixed-header'
      | '/(main)/tables/tbl-height'
      | '/(main)/ui-elements/autocomplete'
      | '/(main)/ui-elements/bottom-sheet'
      | '/(main)/ui-elements/buttons'
      | '/(main)/ui-elements/checkbox'
      | '/(main)/ui-elements/file-input'
      | '/(main)/ui-elements/number-input'
      | '/(main)/ui-elements/otp-input'
      | '/(main)/ui-elements/radio'
      | '/(main)/ui-elements/range-slider'
      | '/(main)/ui-elements/slider'
      | '/(main)/ui-elements/switch'
      | '/(main)/ui-elements/textfield'
      | '/(main)/utils/animation/'
      | '/(main)/utils/colors/'
      | '/(main)/utils/grid/'
      | '/(main)/utils/shadows/'
      | '/(main)/utils/typography/'
      | '/(main)/widget/chart'
      | '/(main)/widget/data'
      | '/(main)/widget/statistics'
    >,
    '/(main)/advance/alert': RouteRecordInfo<
      '/(main)/advance/alert',
      '/advance/alert',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/advance/basic-datatable': RouteRecordInfo<
      '/(main)/advance/basic-datatable',
      '/advance/basic-datatable',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/advance/btn-toggle': RouteRecordInfo<
      '/(main)/advance/btn-toggle',
      '/advance/btn-toggle',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/advance/chip-group': RouteRecordInfo<
      '/(main)/advance/chip-group',
      '/advance/chip-group',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/advance/data-display-datatable': RouteRecordInfo<
      '/(main)/advance/data-display-datatable',
      '/advance/data-display-datatable',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/advance/data-iterator': RouteRecordInfo<
      '/(main)/advance/data-iterator',
      '/advance/data-iterator',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/advance/datepicker': RouteRecordInfo<
      '/(main)/advance/datepicker',
      '/advance/datepicker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/advance/emptystate': RouteRecordInfo<
      '/(main)/advance/emptystate',
      '/advance/emptystate',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/advance/fileupload': RouteRecordInfo<
      '/(main)/advance/fileupload',
      '/advance/fileupload',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/advance/floatingaction': RouteRecordInfo<
      '/(main)/advance/floatingaction',
      '/advance/floatingaction',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/advance/mask-input': RouteRecordInfo<
      '/(main)/advance/mask-input',
      '/advance/mask-input',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/advance/pagination': RouteRecordInfo<
      '/(main)/advance/pagination',
      '/advance/pagination',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/advance/progress': RouteRecordInfo<
      '/(main)/advance/progress',
      '/advance/progress',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/advance/ratings': RouteRecordInfo<
      '/(main)/advance/ratings',
      '/advance/ratings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/advance/server-side-datatable': RouteRecordInfo<
      '/(main)/advance/server-side-datatable',
      '/advance/server-side-datatable',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/advance/snackbar': RouteRecordInfo<
      '/(main)/advance/snackbar',
      '/advance/snackbar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/advance/speeddial': RouteRecordInfo<
      '/(main)/advance/speeddial',
      '/advance/speeddial',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/advance/steppers': RouteRecordInfo<
      '/(main)/advance/steppers',
      '/advance/steppers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/advance/timeline': RouteRecordInfo<
      '/(main)/advance/timeline',
      '/advance/timeline',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/advance/timepicker': RouteRecordInfo<
      '/(main)/advance/timepicker',
      '/advance/timepicker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/advance/treeview': RouteRecordInfo<
      '/(main)/advance/treeview',
      '/advance/treeview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/app/calendar/': RouteRecordInfo<
      '/(main)/app/calendar/',
      '/app/calendar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/app/chats': RouteRecordInfo<
      '/(main)/app/chats',
      '/app/chats',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/app/contact/c-card': RouteRecordInfo<
      '/(main)/app/contact/c-card',
      '/app/contact/c-card',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/app/contact/c-list': RouteRecordInfo<
      '/(main)/app/contact/c-list',
      '/app/contact/c-list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/app/customer/create-invoice': RouteRecordInfo<
      '/(main)/app/customer/create-invoice',
      '/app/customer/create-invoice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/app/customer/customerlist': RouteRecordInfo<
      '/(main)/app/customer/customerlist',
      '/app/customer/customerlist',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/app/customer/order-details': RouteRecordInfo<
      '/(main)/app/customer/order-details',
      '/app/customer/order-details',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/app/customer/orderlist': RouteRecordInfo<
      '/(main)/app/customer/orderlist',
      '/app/customer/orderlist',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/app/customer/productlist': RouteRecordInfo<
      '/(main)/app/customer/productlist',
      '/app/customer/productlist',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/app/customer/productreview': RouteRecordInfo<
      '/(main)/app/customer/productreview',
      '/app/customer/productreview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/app/kanban': RouteRecordInfo<
      '/(main)/app/kanban',
      '/app/kanban',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/app/mail': RouteRecordInfo<
      '/(main)/app/mail',
      '/app/mail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/app/user/account-profile/profile1': RouteRecordInfo<
      '/(main)/app/user/account-profile/profile1',
      '/app/user/account-profile/profile1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/app/user/account-profile/profile2': RouteRecordInfo<
      '/(main)/app/user/account-profile/profile2',
      '/app/user/account-profile/profile2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/app/user/account-profile/profile3': RouteRecordInfo<
      '/(main)/app/user/account-profile/profile3',
      '/app/user/account-profile/profile3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/app/user/card/card1': RouteRecordInfo<
      '/(main)/app/user/card/card1',
      '/app/user/card/card1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/app/user/card/card2': RouteRecordInfo<
      '/(main)/app/user/card/card2',
      '/app/user/card/card2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/app/user/card/card3': RouteRecordInfo<
      '/(main)/app/user/card/card3',
      '/app/user/card/card3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/app/user/list1': RouteRecordInfo<
      '/(main)/app/user/list1',
      '/app/user/list1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/app/user/list2': RouteRecordInfo<
      '/(main)/app/user/list2',
      '/app/user/list2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/app/user/social/followers': RouteRecordInfo<
      '/(main)/app/user/social/followers',
      '/app/user/social/followers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/app/user/social/friend-requests': RouteRecordInfo<
      '/(main)/app/user/social/friend-requests',
      '/app/user/social/friend-requests',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/app/user/social/friends': RouteRecordInfo<
      '/(main)/app/user/social/friends',
      '/app/user/social/friends',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/app/user/social/gallery': RouteRecordInfo<
      '/(main)/app/user/social/gallery',
      '/app/user/social/gallery',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/app/user/social/posts': RouteRecordInfo<
      '/(main)/app/user/social/posts',
      '/app/user/social/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/basic/avatar': RouteRecordInfo<
      '/(main)/basic/avatar',
      '/basic/avatar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/basic/badges': RouteRecordInfo<
      '/(main)/basic/badges',
      '/basic/badges',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/basic/breadcrumb': RouteRecordInfo<
      '/(main)/basic/breadcrumb',
      '/basic/breadcrumb',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/basic/cards': RouteRecordInfo<
      '/(main)/basic/cards',
      '/basic/cards',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/basic/chip': RouteRecordInfo<
      '/(main)/basic/chip',
      '/basic/chip',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/basic/expansion-panel': RouteRecordInfo<
      '/(main)/basic/expansion-panel',
      '/basic/expansion-panel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/basic/parallax': RouteRecordInfo<
      '/(main)/basic/parallax',
      '/basic/parallax',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/basic/tabs': RouteRecordInfo<
      '/(main)/basic/tabs',
      '/basic/tabs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/basic/uilist': RouteRecordInfo<
      '/(main)/basic/uilist',
      '/basic/uilist',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/charts/apex-chart': RouteRecordInfo<
      '/(main)/charts/apex-chart',
      '/charts/apex-chart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/charts/orgchart': RouteRecordInfo<
      '/(main)/charts/orgchart',
      '/charts/orgchart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/charts/pie-chart': RouteRecordInfo<
      '/(main)/charts/pie-chart',
      '/charts/pie-chart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/charts/sparklines': RouteRecordInfo<
      '/(main)/charts/sparklines',
      '/charts/sparklines',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/dashboard/analytics': RouteRecordInfo<
      '/(main)/dashboard/analytics',
      '/dashboard/analytics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/dashboard/default': RouteRecordInfo<
      '/(main)/dashboard/default',
      '/dashboard/default',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/ecommerce/checkout': RouteRecordInfo<
      '/(main)/ecommerce/checkout',
      '/ecommerce/checkout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/ecommerce/product/detail/[id]': RouteRecordInfo<
      '/(main)/ecommerce/product/detail/[id]',
      '/ecommerce/product/detail/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(main)/ecommerce/productlist': RouteRecordInfo<
      '/(main)/ecommerce/productlist',
      '/ecommerce/productlist',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/ecommerce/products': RouteRecordInfo<
      '/(main)/ecommerce/products',
      '/ecommerce/products',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/forms/FormValidation': RouteRecordInfo<
      '/(main)/forms/FormValidation',
      '/forms/FormValidation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/forms/layouts/action-bar': RouteRecordInfo<
      '/(main)/forms/layouts/action-bar',
      '/forms/layouts/action-bar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/forms/layouts/layouts': RouteRecordInfo<
      '/(main)/forms/layouts/layouts',
      '/forms/layouts/layouts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/forms/layouts/multi-column-forms': RouteRecordInfo<
      '/(main)/forms/layouts/multi-column-forms',
      '/forms/layouts/multi-column-forms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/forms/layouts/sticky-action-bar': RouteRecordInfo<
      '/(main)/forms/layouts/sticky-action-bar',
      '/forms/layouts/sticky-action-bar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/forms/plugins/clipboard': RouteRecordInfo<
      '/(main)/forms/plugins/clipboard',
      '/forms/plugins/clipboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/forms/plugins/dropzone': RouteRecordInfo<
      '/(main)/forms/plugins/dropzone',
      '/forms/plugins/dropzone',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/forms/plugins/editor': RouteRecordInfo<
      '/(main)/forms/plugins/editor',
      '/forms/plugins/editor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/forms/plugins/modal': RouteRecordInfo<
      '/(main)/forms/plugins/modal',
      '/forms/plugins/modal',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/forms/plugins/tooltip': RouteRecordInfo<
      '/(main)/forms/plugins/tooltip',
      '/forms/plugins/tooltip',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/pricing/pricing1': RouteRecordInfo<
      '/(main)/pricing/pricing1',
      '/pricing/pricing1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/pricing/pricing2': RouteRecordInfo<
      '/(main)/pricing/pricing2',
      '/pricing/pricing2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/starter': RouteRecordInfo<
      '/(main)/starter',
      '/starter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/tables/tbl-basic': RouteRecordInfo<
      '/(main)/tables/tbl-basic',
      '/tables/tbl-basic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/tables/tbl-dark': RouteRecordInfo<
      '/(main)/tables/tbl-dark',
      '/tables/tbl-dark',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/tables/tbl-density': RouteRecordInfo<
      '/(main)/tables/tbl-density',
      '/tables/tbl-density',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/tables/tbl-fixed-header': RouteRecordInfo<
      '/(main)/tables/tbl-fixed-header',
      '/tables/tbl-fixed-header',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/tables/tbl-height': RouteRecordInfo<
      '/(main)/tables/tbl-height',
      '/tables/tbl-height',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/ui-elements/autocomplete': RouteRecordInfo<
      '/(main)/ui-elements/autocomplete',
      '/ui-elements/autocomplete',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/ui-elements/bottom-sheet': RouteRecordInfo<
      '/(main)/ui-elements/bottom-sheet',
      '/ui-elements/bottom-sheet',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/ui-elements/buttons': RouteRecordInfo<
      '/(main)/ui-elements/buttons',
      '/ui-elements/buttons',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/ui-elements/checkbox': RouteRecordInfo<
      '/(main)/ui-elements/checkbox',
      '/ui-elements/checkbox',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/ui-elements/file-input': RouteRecordInfo<
      '/(main)/ui-elements/file-input',
      '/ui-elements/file-input',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/ui-elements/number-input': RouteRecordInfo<
      '/(main)/ui-elements/number-input',
      '/ui-elements/number-input',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/ui-elements/otp-input': RouteRecordInfo<
      '/(main)/ui-elements/otp-input',
      '/ui-elements/otp-input',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/ui-elements/radio': RouteRecordInfo<
      '/(main)/ui-elements/radio',
      '/ui-elements/radio',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/ui-elements/range-slider': RouteRecordInfo<
      '/(main)/ui-elements/range-slider',
      '/ui-elements/range-slider',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/ui-elements/slider': RouteRecordInfo<
      '/(main)/ui-elements/slider',
      '/ui-elements/slider',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/ui-elements/switch': RouteRecordInfo<
      '/(main)/ui-elements/switch',
      '/ui-elements/switch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/ui-elements/textfield': RouteRecordInfo<
      '/(main)/ui-elements/textfield',
      '/ui-elements/textfield',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/utils/animation/': RouteRecordInfo<
      '/(main)/utils/animation/',
      '/utils/animation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/utils/colors/': RouteRecordInfo<
      '/(main)/utils/colors/',
      '/utils/colors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/utils/grid/': RouteRecordInfo<
      '/(main)/utils/grid/',
      '/utils/grid',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/utils/shadows/': RouteRecordInfo<
      '/(main)/utils/shadows/',
      '/utils/shadows',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/utils/typography/': RouteRecordInfo<
      '/(main)/utils/typography/',
      '/utils/typography',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/widget/chart': RouteRecordInfo<
      '/(main)/widget/chart',
      '/widget/chart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/widget/data': RouteRecordInfo<
      '/(main)/widget/data',
      '/widget/data',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/widget/statistics': RouteRecordInfo<
      '/(main)/widget/statistics',
      '/widget/statistics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth1/check-mail1': RouteRecordInfo<
      '/auth1/check-mail1',
      '/auth1/check-mail1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth1/code-verification': RouteRecordInfo<
      '/auth1/code-verification',
      '/auth1/code-verification',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth1/forgotpwd1': RouteRecordInfo<
      '/auth1/forgotpwd1',
      '/auth1/forgotpwd1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth1/login1': RouteRecordInfo<
      '/auth1/login1',
      '/auth1/login1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth1/register1': RouteRecordInfo<
      '/auth1/register1',
      '/auth1/register1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth1/reset-pwd1': RouteRecordInfo<
      '/auth1/reset-pwd1',
      '/auth1/reset-pwd1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth2/check-mail2': RouteRecordInfo<
      '/auth2/check-mail2',
      '/auth2/check-mail2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth2/code-verification': RouteRecordInfo<
      '/auth2/code-verification',
      '/auth2/code-verification',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth2/forgotpwd2': RouteRecordInfo<
      '/auth2/forgotpwd2',
      '/auth2/forgotpwd2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth2/login2': RouteRecordInfo<
      '/auth2/login2',
      '/auth2/login2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth2/register2': RouteRecordInfo<
      '/auth2/register2',
      '/auth2/register2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth2/reset-pwd2': RouteRecordInfo<
      '/auth2/reset-pwd2',
      '/auth2/reset-pwd2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth3/check-mail3': RouteRecordInfo<
      '/auth3/check-mail3',
      '/auth3/check-mail3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth3/code-verification': RouteRecordInfo<
      '/auth3/code-verification',
      '/auth3/code-verification',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth3/forgotpwd3': RouteRecordInfo<
      '/auth3/forgotpwd3',
      '/auth3/forgotpwd3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth3/login3': RouteRecordInfo<
      '/auth3/login3',
      '/auth3/login3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth3/register3': RouteRecordInfo<
      '/auth3/register3',
      '/auth3/register3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth3/reset-pwd3': RouteRecordInfo<
      '/auth3/reset-pwd3',
      '/auth3/reset-pwd3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/captcha': RouteRecordInfo<
      '/captcha',
      '/captcha',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/contact-us': RouteRecordInfo<
      '/contact-us',
      '/contact-us',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/faq': RouteRecordInfo<
      '/faq',
      '/faq',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/maintenance/comingsoon': RouteRecordInfo<
      '/maintenance/comingsoon',
      '/maintenance/comingsoon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/maintenance/error': RouteRecordInfo<
      '/maintenance/error',
      '/maintenance/error',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/privacy-policy': RouteRecordInfo<
      '/privacy-policy',
      '/privacy-policy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/underconstruction/': RouteRecordInfo<
      '/underconstruction/',
      '/underconstruction',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(main).vue': {
      routes:
        | '/(main)'
        | '/(main)/advance/alert'
        | '/(main)/advance/basic-datatable'
        | '/(main)/advance/btn-toggle'
        | '/(main)/advance/chip-group'
        | '/(main)/advance/data-display-datatable'
        | '/(main)/advance/data-iterator'
        | '/(main)/advance/datepicker'
        | '/(main)/advance/emptystate'
        | '/(main)/advance/fileupload'
        | '/(main)/advance/floatingaction'
        | '/(main)/advance/mask-input'
        | '/(main)/advance/pagination'
        | '/(main)/advance/progress'
        | '/(main)/advance/ratings'
        | '/(main)/advance/server-side-datatable'
        | '/(main)/advance/snackbar'
        | '/(main)/advance/speeddial'
        | '/(main)/advance/steppers'
        | '/(main)/advance/timeline'
        | '/(main)/advance/timepicker'
        | '/(main)/advance/treeview'
        | '/(main)/app/calendar/'
        | '/(main)/app/chats'
        | '/(main)/app/contact/c-card'
        | '/(main)/app/contact/c-list'
        | '/(main)/app/customer/create-invoice'
        | '/(main)/app/customer/customerlist'
        | '/(main)/app/customer/order-details'
        | '/(main)/app/customer/orderlist'
        | '/(main)/app/customer/productlist'
        | '/(main)/app/customer/productreview'
        | '/(main)/app/kanban'
        | '/(main)/app/mail'
        | '/(main)/app/user/account-profile/profile1'
        | '/(main)/app/user/account-profile/profile2'
        | '/(main)/app/user/account-profile/profile3'
        | '/(main)/app/user/card/card1'
        | '/(main)/app/user/card/card2'
        | '/(main)/app/user/card/card3'
        | '/(main)/app/user/list1'
        | '/(main)/app/user/list2'
        | '/(main)/app/user/social/followers'
        | '/(main)/app/user/social/friend-requests'
        | '/(main)/app/user/social/friends'
        | '/(main)/app/user/social/gallery'
        | '/(main)/app/user/social/posts'
        | '/(main)/basic/avatar'
        | '/(main)/basic/badges'
        | '/(main)/basic/breadcrumb'
        | '/(main)/basic/cards'
        | '/(main)/basic/chip'
        | '/(main)/basic/expansion-panel'
        | '/(main)/basic/parallax'
        | '/(main)/basic/tabs'
        | '/(main)/basic/uilist'
        | '/(main)/charts/apex-chart'
        | '/(main)/charts/orgchart'
        | '/(main)/charts/pie-chart'
        | '/(main)/charts/sparklines'
        | '/(main)/dashboard/analytics'
        | '/(main)/dashboard/default'
        | '/(main)/ecommerce/checkout'
        | '/(main)/ecommerce/product/detail/[id]'
        | '/(main)/ecommerce/productlist'
        | '/(main)/ecommerce/products'
        | '/(main)/forms/FormValidation'
        | '/(main)/forms/layouts/action-bar'
        | '/(main)/forms/layouts/layouts'
        | '/(main)/forms/layouts/multi-column-forms'
        | '/(main)/forms/layouts/sticky-action-bar'
        | '/(main)/forms/plugins/clipboard'
        | '/(main)/forms/plugins/dropzone'
        | '/(main)/forms/plugins/editor'
        | '/(main)/forms/plugins/modal'
        | '/(main)/forms/plugins/tooltip'
        | '/(main)/pricing/pricing1'
        | '/(main)/pricing/pricing2'
        | '/(main)/starter'
        | '/(main)/tables/tbl-basic'
        | '/(main)/tables/tbl-dark'
        | '/(main)/tables/tbl-density'
        | '/(main)/tables/tbl-fixed-header'
        | '/(main)/tables/tbl-height'
        | '/(main)/ui-elements/autocomplete'
        | '/(main)/ui-elements/bottom-sheet'
        | '/(main)/ui-elements/buttons'
        | '/(main)/ui-elements/checkbox'
        | '/(main)/ui-elements/file-input'
        | '/(main)/ui-elements/number-input'
        | '/(main)/ui-elements/otp-input'
        | '/(main)/ui-elements/radio'
        | '/(main)/ui-elements/range-slider'
        | '/(main)/ui-elements/slider'
        | '/(main)/ui-elements/switch'
        | '/(main)/ui-elements/textfield'
        | '/(main)/utils/animation/'
        | '/(main)/utils/colors/'
        | '/(main)/utils/grid/'
        | '/(main)/utils/shadows/'
        | '/(main)/utils/typography/'
        | '/(main)/widget/chart'
        | '/(main)/widget/data'
        | '/(main)/widget/statistics'
      views:
        | 'default'
    }
    'src/pages/(main)/advance/alert.vue': {
      routes:
        | '/(main)/advance/alert'
      views:
        | never
    }
    'src/pages/(main)/advance/basic-datatable.vue': {
      routes:
        | '/(main)/advance/basic-datatable'
      views:
        | never
    }
    'src/pages/(main)/advance/btn-toggle.vue': {
      routes:
        | '/(main)/advance/btn-toggle'
      views:
        | never
    }
    'src/pages/(main)/advance/chip-group.vue': {
      routes:
        | '/(main)/advance/chip-group'
      views:
        | never
    }
    'src/pages/(main)/advance/data-display-datatable.vue': {
      routes:
        | '/(main)/advance/data-display-datatable'
      views:
        | never
    }
    'src/pages/(main)/advance/data-iterator.vue': {
      routes:
        | '/(main)/advance/data-iterator'
      views:
        | never
    }
    'src/pages/(main)/advance/datepicker.vue': {
      routes:
        | '/(main)/advance/datepicker'
      views:
        | never
    }
    'src/pages/(main)/advance/emptystate.vue': {
      routes:
        | '/(main)/advance/emptystate'
      views:
        | never
    }
    'src/pages/(main)/advance/fileupload.vue': {
      routes:
        | '/(main)/advance/fileupload'
      views:
        | never
    }
    'src/pages/(main)/advance/floatingaction.vue': {
      routes:
        | '/(main)/advance/floatingaction'
      views:
        | never
    }
    'src/pages/(main)/advance/mask-input.vue': {
      routes:
        | '/(main)/advance/mask-input'
      views:
        | never
    }
    'src/pages/(main)/advance/pagination.vue': {
      routes:
        | '/(main)/advance/pagination'
      views:
        | never
    }
    'src/pages/(main)/advance/progress.vue': {
      routes:
        | '/(main)/advance/progress'
      views:
        | never
    }
    'src/pages/(main)/advance/ratings.vue': {
      routes:
        | '/(main)/advance/ratings'
      views:
        | never
    }
    'src/pages/(main)/advance/server-side-datatable.vue': {
      routes:
        | '/(main)/advance/server-side-datatable'
      views:
        | never
    }
    'src/pages/(main)/advance/snackbar.vue': {
      routes:
        | '/(main)/advance/snackbar'
      views:
        | never
    }
    'src/pages/(main)/advance/speeddial.vue': {
      routes:
        | '/(main)/advance/speeddial'
      views:
        | never
    }
    'src/pages/(main)/advance/steppers.vue': {
      routes:
        | '/(main)/advance/steppers'
      views:
        | never
    }
    'src/pages/(main)/advance/timeline.vue': {
      routes:
        | '/(main)/advance/timeline'
      views:
        | never
    }
    'src/pages/(main)/advance/timepicker.vue': {
      routes:
        | '/(main)/advance/timepicker'
      views:
        | never
    }
    'src/pages/(main)/advance/treeview.vue': {
      routes:
        | '/(main)/advance/treeview'
      views:
        | never
    }
    'src/pages/(main)/app/calendar/index.vue': {
      routes:
        | '/(main)/app/calendar/'
      views:
        | never
    }
    'src/pages/(main)/app/chats.vue': {
      routes:
        | '/(main)/app/chats'
      views:
        | never
    }
    'src/pages/(main)/app/contact/c-card.vue': {
      routes:
        | '/(main)/app/contact/c-card'
      views:
        | never
    }
    'src/pages/(main)/app/contact/c-list.vue': {
      routes:
        | '/(main)/app/contact/c-list'
      views:
        | never
    }
    'src/pages/(main)/app/customer/create-invoice.vue': {
      routes:
        | '/(main)/app/customer/create-invoice'
      views:
        | never
    }
    'src/pages/(main)/app/customer/customerlist.vue': {
      routes:
        | '/(main)/app/customer/customerlist'
      views:
        | never
    }
    'src/pages/(main)/app/customer/order-details.vue': {
      routes:
        | '/(main)/app/customer/order-details'
      views:
        | never
    }
    'src/pages/(main)/app/customer/orderlist.vue': {
      routes:
        | '/(main)/app/customer/orderlist'
      views:
        | never
    }
    'src/pages/(main)/app/customer/productlist.vue': {
      routes:
        | '/(main)/app/customer/productlist'
      views:
        | never
    }
    'src/pages/(main)/app/customer/productreview.vue': {
      routes:
        | '/(main)/app/customer/productreview'
      views:
        | never
    }
    'src/pages/(main)/app/kanban.vue': {
      routes:
        | '/(main)/app/kanban'
      views:
        | never
    }
    'src/pages/(main)/app/mail.vue': {
      routes:
        | '/(main)/app/mail'
      views:
        | never
    }
    'src/pages/(main)/app/user/account-profile/profile1.vue': {
      routes:
        | '/(main)/app/user/account-profile/profile1'
      views:
        | never
    }
    'src/pages/(main)/app/user/account-profile/profile2.vue': {
      routes:
        | '/(main)/app/user/account-profile/profile2'
      views:
        | never
    }
    'src/pages/(main)/app/user/account-profile/profile3.vue': {
      routes:
        | '/(main)/app/user/account-profile/profile3'
      views:
        | never
    }
    'src/pages/(main)/app/user/card/card1.vue': {
      routes:
        | '/(main)/app/user/card/card1'
      views:
        | never
    }
    'src/pages/(main)/app/user/card/card2.vue': {
      routes:
        | '/(main)/app/user/card/card2'
      views:
        | never
    }
    'src/pages/(main)/app/user/card/card3.vue': {
      routes:
        | '/(main)/app/user/card/card3'
      views:
        | never
    }
    'src/pages/(main)/app/user/list1.vue': {
      routes:
        | '/(main)/app/user/list1'
      views:
        | never
    }
    'src/pages/(main)/app/user/list2.vue': {
      routes:
        | '/(main)/app/user/list2'
      views:
        | never
    }
    'src/pages/(main)/app/user/social/followers.vue': {
      routes:
        | '/(main)/app/user/social/followers'
      views:
        | never
    }
    'src/pages/(main)/app/user/social/friend-requests.vue': {
      routes:
        | '/(main)/app/user/social/friend-requests'
      views:
        | never
    }
    'src/pages/(main)/app/user/social/friends.vue': {
      routes:
        | '/(main)/app/user/social/friends'
      views:
        | never
    }
    'src/pages/(main)/app/user/social/gallery.vue': {
      routes:
        | '/(main)/app/user/social/gallery'
      views:
        | never
    }
    'src/pages/(main)/app/user/social/posts.vue': {
      routes:
        | '/(main)/app/user/social/posts'
      views:
        | never
    }
    'src/pages/(main)/basic/avatar.vue': {
      routes:
        | '/(main)/basic/avatar'
      views:
        | never
    }
    'src/pages/(main)/basic/badges.vue': {
      routes:
        | '/(main)/basic/badges'
      views:
        | never
    }
    'src/pages/(main)/basic/breadcrumb.vue': {
      routes:
        | '/(main)/basic/breadcrumb'
      views:
        | never
    }
    'src/pages/(main)/basic/cards.vue': {
      routes:
        | '/(main)/basic/cards'
      views:
        | never
    }
    'src/pages/(main)/basic/chip.vue': {
      routes:
        | '/(main)/basic/chip'
      views:
        | never
    }
    'src/pages/(main)/basic/expansion-panel.vue': {
      routes:
        | '/(main)/basic/expansion-panel'
      views:
        | never
    }
    'src/pages/(main)/basic/parallax.vue': {
      routes:
        | '/(main)/basic/parallax'
      views:
        | never
    }
    'src/pages/(main)/basic/tabs.vue': {
      routes:
        | '/(main)/basic/tabs'
      views:
        | never
    }
    'src/pages/(main)/basic/uilist.vue': {
      routes:
        | '/(main)/basic/uilist'
      views:
        | never
    }
    'src/pages/(main)/charts/apex-chart.vue': {
      routes:
        | '/(main)/charts/apex-chart'
      views:
        | never
    }
    'src/pages/(main)/charts/orgchart.vue': {
      routes:
        | '/(main)/charts/orgchart'
      views:
        | never
    }
    'src/pages/(main)/charts/pie-chart.vue': {
      routes:
        | '/(main)/charts/pie-chart'
      views:
        | never
    }
    'src/pages/(main)/charts/sparklines.vue': {
      routes:
        | '/(main)/charts/sparklines'
      views:
        | never
    }
    'src/pages/(main)/dashboard/analytics.vue': {
      routes:
        | '/(main)/dashboard/analytics'
      views:
        | never
    }
    'src/pages/(main)/dashboard/default.vue': {
      routes:
        | '/(main)/dashboard/default'
      views:
        | never
    }
    'src/pages/(main)/ecommerce/checkout.vue': {
      routes:
        | '/(main)/ecommerce/checkout'
      views:
        | never
    }
    'src/pages/(main)/ecommerce/product/detail/[id].vue': {
      routes:
        | '/(main)/ecommerce/product/detail/[id]'
      views:
        | never
    }
    'src/pages/(main)/ecommerce/productlist.vue': {
      routes:
        | '/(main)/ecommerce/productlist'
      views:
        | never
    }
    'src/pages/(main)/ecommerce/products.vue': {
      routes:
        | '/(main)/ecommerce/products'
      views:
        | never
    }
    'src/pages/(main)/forms/FormValidation.vue': {
      routes:
        | '/(main)/forms/FormValidation'
      views:
        | never
    }
    'src/pages/(main)/forms/layouts/action-bar.vue': {
      routes:
        | '/(main)/forms/layouts/action-bar'
      views:
        | never
    }
    'src/pages/(main)/forms/layouts/layouts.vue': {
      routes:
        | '/(main)/forms/layouts/layouts'
      views:
        | never
    }
    'src/pages/(main)/forms/layouts/multi-column-forms.vue': {
      routes:
        | '/(main)/forms/layouts/multi-column-forms'
      views:
        | never
    }
    'src/pages/(main)/forms/layouts/sticky-action-bar.vue': {
      routes:
        | '/(main)/forms/layouts/sticky-action-bar'
      views:
        | never
    }
    'src/pages/(main)/forms/plugins/clipboard.vue': {
      routes:
        | '/(main)/forms/plugins/clipboard'
      views:
        | never
    }
    'src/pages/(main)/forms/plugins/dropzone.vue': {
      routes:
        | '/(main)/forms/plugins/dropzone'
      views:
        | never
    }
    'src/pages/(main)/forms/plugins/editor.vue': {
      routes:
        | '/(main)/forms/plugins/editor'
      views:
        | never
    }
    'src/pages/(main)/forms/plugins/modal.vue': {
      routes:
        | '/(main)/forms/plugins/modal'
      views:
        | never
    }
    'src/pages/(main)/forms/plugins/tooltip.vue': {
      routes:
        | '/(main)/forms/plugins/tooltip'
      views:
        | never
    }
    'src/pages/(main)/pricing/pricing1.vue': {
      routes:
        | '/(main)/pricing/pricing1'
      views:
        | never
    }
    'src/pages/(main)/pricing/pricing2.vue': {
      routes:
        | '/(main)/pricing/pricing2'
      views:
        | never
    }
    'src/pages/(main)/starter.vue': {
      routes:
        | '/(main)/starter'
      views:
        | never
    }
    'src/pages/(main)/tables/tbl-basic.vue': {
      routes:
        | '/(main)/tables/tbl-basic'
      views:
        | never
    }
    'src/pages/(main)/tables/tbl-dark.vue': {
      routes:
        | '/(main)/tables/tbl-dark'
      views:
        | never
    }
    'src/pages/(main)/tables/tbl-density.vue': {
      routes:
        | '/(main)/tables/tbl-density'
      views:
        | never
    }
    'src/pages/(main)/tables/tbl-fixed-header.vue': {
      routes:
        | '/(main)/tables/tbl-fixed-header'
      views:
        | never
    }
    'src/pages/(main)/tables/tbl-height.vue': {
      routes:
        | '/(main)/tables/tbl-height'
      views:
        | never
    }
    'src/pages/(main)/ui-elements/autocomplete.vue': {
      routes:
        | '/(main)/ui-elements/autocomplete'
      views:
        | never
    }
    'src/pages/(main)/ui-elements/bottom-sheet.vue': {
      routes:
        | '/(main)/ui-elements/bottom-sheet'
      views:
        | never
    }
    'src/pages/(main)/ui-elements/buttons.vue': {
      routes:
        | '/(main)/ui-elements/buttons'
      views:
        | never
    }
    'src/pages/(main)/ui-elements/checkbox.vue': {
      routes:
        | '/(main)/ui-elements/checkbox'
      views:
        | never
    }
    'src/pages/(main)/ui-elements/file-input.vue': {
      routes:
        | '/(main)/ui-elements/file-input'
      views:
        | never
    }
    'src/pages/(main)/ui-elements/number-input.vue': {
      routes:
        | '/(main)/ui-elements/number-input'
      views:
        | never
    }
    'src/pages/(main)/ui-elements/otp-input.vue': {
      routes:
        | '/(main)/ui-elements/otp-input'
      views:
        | never
    }
    'src/pages/(main)/ui-elements/radio.vue': {
      routes:
        | '/(main)/ui-elements/radio'
      views:
        | never
    }
    'src/pages/(main)/ui-elements/range-slider.vue': {
      routes:
        | '/(main)/ui-elements/range-slider'
      views:
        | never
    }
    'src/pages/(main)/ui-elements/slider.vue': {
      routes:
        | '/(main)/ui-elements/slider'
      views:
        | never
    }
    'src/pages/(main)/ui-elements/switch.vue': {
      routes:
        | '/(main)/ui-elements/switch'
      views:
        | never
    }
    'src/pages/(main)/ui-elements/textfield.vue': {
      routes:
        | '/(main)/ui-elements/textfield'
      views:
        | never
    }
    'src/pages/(main)/utils/animation/index.vue': {
      routes:
        | '/(main)/utils/animation/'
      views:
        | never
    }
    'src/pages/(main)/utils/colors/index.vue': {
      routes:
        | '/(main)/utils/colors/'
      views:
        | never
    }
    'src/pages/(main)/utils/grid/index.vue': {
      routes:
        | '/(main)/utils/grid/'
      views:
        | never
    }
    'src/pages/(main)/utils/shadows/index.vue': {
      routes:
        | '/(main)/utils/shadows/'
      views:
        | never
    }
    'src/pages/(main)/utils/typography/index.vue': {
      routes:
        | '/(main)/utils/typography/'
      views:
        | never
    }
    'src/pages/(main)/widget/chart.vue': {
      routes:
        | '/(main)/widget/chart'
      views:
        | never
    }
    'src/pages/(main)/widget/data.vue': {
      routes:
        | '/(main)/widget/data'
      views:
        | never
    }
    'src/pages/(main)/widget/statistics.vue': {
      routes:
        | '/(main)/widget/statistics'
      views:
        | never
    }
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/auth1/check-mail1.vue': {
      routes:
        | '/auth1/check-mail1'
      views:
        | never
    }
    'src/pages/auth1/code-verification.vue': {
      routes:
        | '/auth1/code-verification'
      views:
        | never
    }
    'src/pages/auth1/forgotpwd1.vue': {
      routes:
        | '/auth1/forgotpwd1'
      views:
        | never
    }
    'src/pages/auth1/login1.vue': {
      routes:
        | '/auth1/login1'
      views:
        | never
    }
    'src/pages/auth1/register1.vue': {
      routes:
        | '/auth1/register1'
      views:
        | never
    }
    'src/pages/auth1/reset-pwd1.vue': {
      routes:
        | '/auth1/reset-pwd1'
      views:
        | never
    }
    'src/pages/auth2/check-mail2.vue': {
      routes:
        | '/auth2/check-mail2'
      views:
        | never
    }
    'src/pages/auth2/code-verification.vue': {
      routes:
        | '/auth2/code-verification'
      views:
        | never
    }
    'src/pages/auth2/forgotpwd2.vue': {
      routes:
        | '/auth2/forgotpwd2'
      views:
        | never
    }
    'src/pages/auth2/login2.vue': {
      routes:
        | '/auth2/login2'
      views:
        | never
    }
    'src/pages/auth2/register2.vue': {
      routes:
        | '/auth2/register2'
      views:
        | never
    }
    'src/pages/auth2/reset-pwd2.vue': {
      routes:
        | '/auth2/reset-pwd2'
      views:
        | never
    }
    'src/pages/auth3/check-mail3.vue': {
      routes:
        | '/auth3/check-mail3'
      views:
        | never
    }
    'src/pages/auth3/code-verification.vue': {
      routes:
        | '/auth3/code-verification'
      views:
        | never
    }
    'src/pages/auth3/forgotpwd3.vue': {
      routes:
        | '/auth3/forgotpwd3'
      views:
        | never
    }
    'src/pages/auth3/login3.vue': {
      routes:
        | '/auth3/login3'
      views:
        | never
    }
    'src/pages/auth3/register3.vue': {
      routes:
        | '/auth3/register3'
      views:
        | never
    }
    'src/pages/auth3/reset-pwd3.vue': {
      routes:
        | '/auth3/reset-pwd3'
      views:
        | never
    }
    'src/pages/captcha.vue': {
      routes:
        | '/captcha'
      views:
        | never
    }
    'src/pages/contact-us.vue': {
      routes:
        | '/contact-us'
      views:
        | never
    }
    'src/pages/faq.vue': {
      routes:
        | '/faq'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/maintenance/comingsoon.vue': {
      routes:
        | '/maintenance/comingsoon'
      views:
        | never
    }
    'src/pages/maintenance/error.vue': {
      routes:
        | '/maintenance/error'
      views:
        | never
    }
    'src/pages/privacy-policy.vue': {
      routes:
        | '/privacy-policy'
      views:
        | never
    }
    'src/pages/underconstruction/index.vue': {
      routes:
        | '/underconstruction/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
